name: bottom_navigation_riverpod
description: Bottom navigation with multiple beamers, login guard, and navigation state managed by riverpod.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  beamer:
    path: ../../package

  cupertino_icons: ^1.0.3
  flutter_riverpod: ^2.3.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
